project_id = "ciwxprvroidocmtzjviu"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false

[functions.create-company]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.register-company]
verify_jwt = false

[functions.whatsapp-oauth-callback]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = false
